/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewNotebookIdRouteImport } from './routes/review.$notebookId'
import { Route as NotebookIdRouteImport } from './routes/notebook.$id'
import { Route as DocumentIdRouteImport } from './routes/document.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewNotebookIdRoute = ReviewNotebookIdRouteImport.update({
  id: '/review/$notebookId',
  path: '/review/$notebookId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIdRoute = NotebookIdRouteImport.update({
  id: '/notebook/$id',
  path: '/notebook/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentIdRoute = DocumentIdRouteImport.update({
  id: '/document/$id',
  path: '/document/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/document/$id': typeof DocumentIdRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/review/$notebookId': typeof ReviewNotebookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/document/$id': typeof DocumentIdRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/review/$notebookId': typeof ReviewNotebookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/document/$id': typeof DocumentIdRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/review/$notebookId': typeof ReviewNotebookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/document/$id'
    | '/notebook/$id'
    | '/review/$notebookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/document/$id'
    | '/notebook/$id'
    | '/review/$notebookId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/document/$id'
    | '/notebook/$id'
    | '/review/$notebookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DocumentIdRoute: typeof DocumentIdRoute
  NotebookIdRoute: typeof NotebookIdRoute
  ReviewNotebookIdRoute: typeof ReviewNotebookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$notebookId': {
      id: '/review/$notebookId'
      path: '/review/$notebookId'
      fullPath: '/review/$notebookId'
      preLoaderRoute: typeof ReviewNotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/$id': {
      id: '/notebook/$id'
      path: '/notebook/$id'
      fullPath: '/notebook/$id'
      preLoaderRoute: typeof NotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$id': {
      id: '/document/$id'
      path: '/document/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof DocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DocumentIdRoute: DocumentIdRoute,
  NotebookIdRoute: NotebookIdRoute,
  ReviewNotebookIdRoute: ReviewNotebookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
