/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayRouteImport } from './routes/play'
import { Route as IqRouteImport } from './routes/iq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IqIndexRouteImport } from './routes/iq.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ReviewNotebookIdRouteImport } from './routes/review.$notebookId'
import { Route as PlayRoomIdRouteImport } from './routes/play.$roomId'
import { Route as NotebookIdRouteImport } from './routes/notebook.$id'
import { Route as IqInicioRouteImport } from './routes/iq.inicio'
import { Route as IqHistorialRouteImport } from './routes/iq.historial'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as DocumentIdRouteImport } from './routes/document.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api.sitemap[.]xml'
import { Route as IqTestIntentoIdRouteImport } from './routes/iq.test.$intentoId'
import { Route as IqResultadoIntentoIdRouteImport } from './routes/iq.resultado.$intentoId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const IqRoute = IqRouteImport.update({
  id: '/iq',
  path: '/iq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IqIndexRoute = IqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IqRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewNotebookIdRoute = ReviewNotebookIdRouteImport.update({
  id: '/review/$notebookId',
  path: '/review/$notebookId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoomIdRoute = PlayRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => PlayRoute,
} as any)
const NotebookIdRoute = NotebookIdRouteImport.update({
  id: '/notebook/$id',
  path: '/notebook/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IqInicioRoute = IqInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => IqRoute,
} as any)
const IqHistorialRoute = IqHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => IqRoute,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentIdRoute = DocumentIdRouteImport.update({
  id: '/document/$id',
  path: '/document/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IqTestIntentoIdRoute = IqTestIntentoIdRouteImport.update({
  id: '/test/$intentoId',
  path: '/test/$intentoId',
  getParentRoute: () => IqRoute,
} as any)
const IqResultadoIntentoIdRoute = IqResultadoIntentoIdRouteImport.update({
  id: '/resultado/$intentoId',
  path: '/resultado/$intentoId',
  getParentRoute: () => IqRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/iq': typeof IqRouteWithChildren
  '/play': typeof PlayRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/document/$id': typeof DocumentIdRoute
  '/editor/$id': typeof EditorIdRoute
  '/iq/historial': typeof IqHistorialRoute
  '/iq/inicio': typeof IqInicioRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/review/$notebookId': typeof ReviewNotebookIdRoute
  '/blog/': typeof BlogIndexRoute
  '/iq/': typeof IqIndexRoute
  '/iq/resultado/$intentoId': typeof IqResultadoIntentoIdRoute
  '/iq/test/$intentoId': typeof IqTestIntentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/play': typeof PlayRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/document/$id': typeof DocumentIdRoute
  '/editor/$id': typeof EditorIdRoute
  '/iq/historial': typeof IqHistorialRoute
  '/iq/inicio': typeof IqInicioRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/review/$notebookId': typeof ReviewNotebookIdRoute
  '/blog': typeof BlogIndexRoute
  '/iq': typeof IqIndexRoute
  '/iq/resultado/$intentoId': typeof IqResultadoIntentoIdRoute
  '/iq/test/$intentoId': typeof IqTestIntentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/iq': typeof IqRouteWithChildren
  '/play': typeof PlayRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/document/$id': typeof DocumentIdRoute
  '/editor/$id': typeof EditorIdRoute
  '/iq/historial': typeof IqHistorialRoute
  '/iq/inicio': typeof IqInicioRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/review/$notebookId': typeof ReviewNotebookIdRoute
  '/blog/': typeof BlogIndexRoute
  '/iq/': typeof IqIndexRoute
  '/iq/resultado/$intentoId': typeof IqResultadoIntentoIdRoute
  '/iq/test/$intentoId': typeof IqTestIntentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/iq'
    | '/play'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/document/$id'
    | '/editor/$id'
    | '/iq/historial'
    | '/iq/inicio'
    | '/notebook/$id'
    | '/play/$roomId'
    | '/review/$notebookId'
    | '/blog/'
    | '/iq/'
    | '/iq/resultado/$intentoId'
    | '/iq/test/$intentoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/play'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/document/$id'
    | '/editor/$id'
    | '/iq/historial'
    | '/iq/inicio'
    | '/notebook/$id'
    | '/play/$roomId'
    | '/review/$notebookId'
    | '/blog'
    | '/iq'
    | '/iq/resultado/$intentoId'
    | '/iq/test/$intentoId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/iq'
    | '/play'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/document/$id'
    | '/editor/$id'
    | '/iq/historial'
    | '/iq/inicio'
    | '/notebook/$id'
    | '/play/$roomId'
    | '/review/$notebookId'
    | '/blog/'
    | '/iq/'
    | '/iq/resultado/$intentoId'
    | '/iq/test/$intentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  IqRoute: typeof IqRouteWithChildren
  PlayRoute: typeof PlayRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DocumentIdRoute: typeof DocumentIdRoute
  EditorIdRoute: typeof EditorIdRoute
  NotebookIdRoute: typeof NotebookIdRoute
  ReviewNotebookIdRoute: typeof ReviewNotebookIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iq': {
      id: '/iq'
      path: '/iq'
      fullPath: '/iq'
      preLoaderRoute: typeof IqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iq/': {
      id: '/iq/'
      path: '/'
      fullPath: '/iq/'
      preLoaderRoute: typeof IqIndexRouteImport
      parentRoute: typeof IqRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$notebookId': {
      id: '/review/$notebookId'
      path: '/review/$notebookId'
      fullPath: '/review/$notebookId'
      preLoaderRoute: typeof ReviewNotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$roomId': {
      id: '/play/$roomId'
      path: '/$roomId'
      fullPath: '/play/$roomId'
      preLoaderRoute: typeof PlayRoomIdRouteImport
      parentRoute: typeof PlayRoute
    }
    '/notebook/$id': {
      id: '/notebook/$id'
      path: '/notebook/$id'
      fullPath: '/notebook/$id'
      preLoaderRoute: typeof NotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iq/inicio': {
      id: '/iq/inicio'
      path: '/inicio'
      fullPath: '/iq/inicio'
      preLoaderRoute: typeof IqInicioRouteImport
      parentRoute: typeof IqRoute
    }
    '/iq/historial': {
      id: '/iq/historial'
      path: '/historial'
      fullPath: '/iq/historial'
      preLoaderRoute: typeof IqHistorialRouteImport
      parentRoute: typeof IqRoute
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$id': {
      id: '/document/$id'
      path: '/document/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof DocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iq/test/$intentoId': {
      id: '/iq/test/$intentoId'
      path: '/test/$intentoId'
      fullPath: '/iq/test/$intentoId'
      preLoaderRoute: typeof IqTestIntentoIdRouteImport
      parentRoute: typeof IqRoute
    }
    '/iq/resultado/$intentoId': {
      id: '/iq/resultado/$intentoId'
      path: '/resultado/$intentoId'
      fullPath: '/iq/resultado/$intentoId'
      preLoaderRoute: typeof IqResultadoIntentoIdRouteImport
      parentRoute: typeof IqRoute
    }
  }
}

interface IqRouteChildren {
  IqHistorialRoute: typeof IqHistorialRoute
  IqInicioRoute: typeof IqInicioRoute
  IqIndexRoute: typeof IqIndexRoute
  IqResultadoIntentoIdRoute: typeof IqResultadoIntentoIdRoute
  IqTestIntentoIdRoute: typeof IqTestIntentoIdRoute
}

const IqRouteChildren: IqRouteChildren = {
  IqHistorialRoute: IqHistorialRoute,
  IqInicioRoute: IqInicioRoute,
  IqIndexRoute: IqIndexRoute,
  IqResultadoIntentoIdRoute: IqResultadoIntentoIdRoute,
  IqTestIntentoIdRoute: IqTestIntentoIdRoute,
}

const IqRouteWithChildren = IqRoute._addFileChildren(IqRouteChildren)

interface PlayRouteChildren {
  PlayRoomIdRoute: typeof PlayRoomIdRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayRoomIdRoute: PlayRoomIdRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  IqRoute: IqRouteWithChildren,
  PlayRoute: PlayRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  DocumentIdRoute: DocumentIdRoute,
  EditorIdRoute: EditorIdRoute,
  NotebookIdRoute: NotebookIdRoute,
  ReviewNotebookIdRoute: ReviewNotebookIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
