/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as IqRouteImport } from './routes/iq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewNotebookIdRouteImport } from './routes/review.$notebookId'
import { Route as PlayRoomIdRouteImport } from './routes/play.$roomId'
import { Route as NotebookIdRouteImport } from './routes/notebook.$id'
import { Route as IqInicioRouteImport } from './routes/iq.inicio'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as DocumentIdRouteImport } from './routes/document.$id'
import { Route as IqTestIntentoIdRouteImport } from './routes/iq.test.$intentoId'
import { Route as IqResultadoIntentoIdRouteImport } from './routes/iq.resultado.$intentoId'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const IqRoute = IqRouteImport.update({
  id: '/iq',
  path: '/iq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewNotebookIdRoute = ReviewNotebookIdRouteImport.update({
  id: '/review/$notebookId',
  path: '/review/$notebookId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoomIdRoute = PlayRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => PlayRoute,
} as any)
const NotebookIdRoute = NotebookIdRouteImport.update({
  id: '/notebook/$id',
  path: '/notebook/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IqInicioRoute = IqInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => IqRoute,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentIdRoute = DocumentIdRouteImport.update({
  id: '/document/$id',
  path: '/document/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IqTestIntentoIdRoute = IqTestIntentoIdRouteImport.update({
  id: '/test/$intentoId',
  path: '/test/$intentoId',
  getParentRoute: () => IqRoute,
} as any)
const IqResultadoIntentoIdRoute = IqResultadoIntentoIdRouteImport.update({
  id: '/resultado/$intentoId',
  path: '/resultado/$intentoId',
  getParentRoute: () => IqRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/iq': typeof IqRouteWithChildren
  '/play': typeof PlayRouteWithChildren
  '/document/$id': typeof DocumentIdRoute
  '/editor/$id': typeof EditorIdRoute
  '/iq/inicio': typeof IqInicioRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/review/$notebookId': typeof ReviewNotebookIdRoute
  '/iq/resultado/$intentoId': typeof IqResultadoIntentoIdRoute
  '/iq/test/$intentoId': typeof IqTestIntentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/iq': typeof IqRouteWithChildren
  '/play': typeof PlayRouteWithChildren
  '/document/$id': typeof DocumentIdRoute
  '/editor/$id': typeof EditorIdRoute
  '/iq/inicio': typeof IqInicioRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/review/$notebookId': typeof ReviewNotebookIdRoute
  '/iq/resultado/$intentoId': typeof IqResultadoIntentoIdRoute
  '/iq/test/$intentoId': typeof IqTestIntentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/iq': typeof IqRouteWithChildren
  '/play': typeof PlayRouteWithChildren
  '/document/$id': typeof DocumentIdRoute
  '/editor/$id': typeof EditorIdRoute
  '/iq/inicio': typeof IqInicioRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/review/$notebookId': typeof ReviewNotebookIdRoute
  '/iq/resultado/$intentoId': typeof IqResultadoIntentoIdRoute
  '/iq/test/$intentoId': typeof IqTestIntentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/iq'
    | '/play'
    | '/document/$id'
    | '/editor/$id'
    | '/iq/inicio'
    | '/notebook/$id'
    | '/play/$roomId'
    | '/review/$notebookId'
    | '/iq/resultado/$intentoId'
    | '/iq/test/$intentoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/iq'
    | '/play'
    | '/document/$id'
    | '/editor/$id'
    | '/iq/inicio'
    | '/notebook/$id'
    | '/play/$roomId'
    | '/review/$notebookId'
    | '/iq/resultado/$intentoId'
    | '/iq/test/$intentoId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/iq'
    | '/play'
    | '/document/$id'
    | '/editor/$id'
    | '/iq/inicio'
    | '/notebook/$id'
    | '/play/$roomId'
    | '/review/$notebookId'
    | '/iq/resultado/$intentoId'
    | '/iq/test/$intentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  IqRoute: typeof IqRouteWithChildren
  PlayRoute: typeof PlayRouteWithChildren
  DocumentIdRoute: typeof DocumentIdRoute
  EditorIdRoute: typeof EditorIdRoute
  NotebookIdRoute: typeof NotebookIdRoute
  ReviewNotebookIdRoute: typeof ReviewNotebookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iq': {
      id: '/iq'
      path: '/iq'
      fullPath: '/iq'
      preLoaderRoute: typeof IqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$notebookId': {
      id: '/review/$notebookId'
      path: '/review/$notebookId'
      fullPath: '/review/$notebookId'
      preLoaderRoute: typeof ReviewNotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$roomId': {
      id: '/play/$roomId'
      path: '/$roomId'
      fullPath: '/play/$roomId'
      preLoaderRoute: typeof PlayRoomIdRouteImport
      parentRoute: typeof PlayRoute
    }
    '/notebook/$id': {
      id: '/notebook/$id'
      path: '/notebook/$id'
      fullPath: '/notebook/$id'
      preLoaderRoute: typeof NotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iq/inicio': {
      id: '/iq/inicio'
      path: '/inicio'
      fullPath: '/iq/inicio'
      preLoaderRoute: typeof IqInicioRouteImport
      parentRoute: typeof IqRoute
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$id': {
      id: '/document/$id'
      path: '/document/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof DocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iq/test/$intentoId': {
      id: '/iq/test/$intentoId'
      path: '/test/$intentoId'
      fullPath: '/iq/test/$intentoId'
      preLoaderRoute: typeof IqTestIntentoIdRouteImport
      parentRoute: typeof IqRoute
    }
    '/iq/resultado/$intentoId': {
      id: '/iq/resultado/$intentoId'
      path: '/resultado/$intentoId'
      fullPath: '/iq/resultado/$intentoId'
      preLoaderRoute: typeof IqResultadoIntentoIdRouteImport
      parentRoute: typeof IqRoute
    }
  }
}

interface IqRouteChildren {
  IqInicioRoute: typeof IqInicioRoute
  IqResultadoIntentoIdRoute: typeof IqResultadoIntentoIdRoute
  IqTestIntentoIdRoute: typeof IqTestIntentoIdRoute
}

const IqRouteChildren: IqRouteChildren = {
  IqInicioRoute: IqInicioRoute,
  IqResultadoIntentoIdRoute: IqResultadoIntentoIdRoute,
  IqTestIntentoIdRoute: IqTestIntentoIdRoute,
}

const IqRouteWithChildren = IqRoute._addFileChildren(IqRouteChildren)

interface PlayRouteChildren {
  PlayRoomIdRoute: typeof PlayRoomIdRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayRoomIdRoute: PlayRoomIdRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  IqRoute: IqRouteWithChildren,
  PlayRoute: PlayRouteWithChildren,
  DocumentIdRoute: DocumentIdRoute,
  EditorIdRoute: EditorIdRoute,
  NotebookIdRoute: NotebookIdRoute,
  ReviewNotebookIdRoute: ReviewNotebookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
